# Set the version of docker compose to use
version: "3.8"

# The containers that compose the project
services:
  db:
    image: postgres:15
    restart: always
    container_name: nest_react_development
    ports:
      - "54320:5432"
    environment:
      TZ: "UTC"
      PGTZ: "UTC"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest_react_development
  test:
    image: postgres:15
    restart: always
    container_name: nest_react_test
    ports:
      - "54321:5432"
    environment:
      TZ: "UTC"
      PGTZ: "UTC"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest_react_test
